apiVersion: v2
name: onecx-welcome-ui
version: 0.0.0
description: OneCX Welcome UI.
home: https://github.com/onecx/onecx-welcome-ui
keywords:
  - welcome
sources:
  - https://github.com/onecx/onecx-welcome-ui
maintainers:
  - name: OneCX Developer Team
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-angular-app
    version: ^0
    repository: oci://ghcr.io/onecx/charts
    alias: app
